name: notebook-pr
on:
  pull_request:
    branches: main
    paths: '**/*.ipynb'

env:
  NB_KERNEL: python
  NMA_REPO: course-content
  NMA_MAIN_BRANCH: main

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      notebooks: ${{ steps.set-matrix.outputs.notebooks }}
      has_notebooks: ${{ steps.set-matrix.outputs.has_notebooks }}
      commit_message: ${{ steps.get-commit.outputs.message }}
      materials_changed: ${{ steps.materials-check.outputs.materials_changed }}
      skip_ci: ${{ steps.check-skip.outputs.skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get commit message
        id: get-commit
        run: |
          msg=$(git log -1 --pretty=format:"%s")
          echo "message=$msg" >> $GITHUB_OUTPUT

      - name: Check skip ci
        id: check-skip
        env:
          COMMIT_MESSAGE: ${{ steps.get-commit.outputs.message }}
        run: |
          if [[ "$COMMIT_MESSAGE" == *"skip ci"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Python environment
        if: steps.check-skip.outputs.skip != 'true'
        uses: ./.github/actions/setup-python-env

      - name: Setup CI tools
        if: steps.check-skip.outputs.skip != 'true'
        uses: ./.github/actions/setup-ci-tools
        with:
          commit-message: ${{ steps.get-commit.outputs.message }}

      - name: Setup rendering dependencies
        if: steps.check-skip.outputs.skip != 'true'
        uses: ./.github/actions/setup-rendering-deps

      - name: Get changed files
        if: steps.check-skip.outputs.skip != 'true'
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Check if materials.yml changed
        id: materials-check
        if: steps.check-skip.outputs.skip != 'true'
        run: |
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" =~ materials\.yml ]]; then
            echo "materials_changed=true" >> $GITHUB_OUTPUT
          else
            echo "materials_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set notebook matrix
        id: set-matrix
        if: steps.check-skip.outputs.skip != 'true'
        run: |
          nbs=$(python ci/select_notebooks.py ${{ steps.changed-files.outputs.all_changed_files }})

          if [ -z "$nbs" ]; then
            echo "No notebooks to process"
            echo "has_notebooks=false" >> $GITHUB_OUTPUT
            echo "notebooks=[]" >> $GITHUB_OUTPUT
          else
            echo "Notebooks to process: $nbs"
            echo "has_notebooks=true" >> $GITHUB_OUTPUT
            json_array=$(echo "$nbs" | tr ' ' '\n' | jq -R . | jq -s -c .)
            echo "notebooks=$json_array" >> $GITHUB_OUTPUT
          fi
